    One hot representation

In [8]:
from tensorflow.keras.preprocessing.text import one_hot

### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

## Define the vocabulary size
voc_size=10000

### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent] # While doing this one hot encoding technique in keras we pass the parameters as words & vocabulary size.
one_hot_repr

## Ex - 2172 assigns the index number of the word 'the' in the vocabulary. This means index 2172 is assigned as 1 & other indexes are considered as 0.

[[8964, 5980, 4592, 9807],
 [8964, 5980, 4592, 9363],
 [8964, 2971, 4592, 5203],
 [4338, 1922, 5016, 6685, 7011],
 [4338, 1922, 5016, 6685, 3310],
 [4656, 8964, 6462, 4592, 1124],
 [8386, 2215, 1355, 6685]]

Word embedding representaion 

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

sent_length=8 # Step 1 : Make sentences of equal size.
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) # Adding some pads before the sentences to make it equal to maximum decided length.
print(embedded_docs)

[[   0    0    0    0 8964 5980 4592 9807]
 [   0    0    0    0 8964 5980 4592 9363]
 [   0    0    0    0 8964 2971 4592 5203]
 [   0    0    0 4338 1922 5016 6685 7011]
 [   0    0    0 4338 1922 5016 6685 3310]
 [   0    0    0 4656 8964 6462 4592 1124]
 [   0    0    0    0 8386 2215 1355 6685]]


In [10]:
## feature representation allows to assign selected features to the whole vocabulary. 
dim=10

## Sequential model to use embedding layer.

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length)) ## Passing vocabulary size = 10000 , dimmensions/features = 10, sentence length.
model.compile('adam','mse') # Output layer
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs) ## Each of the 10,000 words are assigned to 10 unique features & the values show the relation between them.
## (Ex - one of our feature is Gender then how does it associates with a word mentioned in vocabulary.There could be some huge relations or else negative or no correlation.  )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


array([[[ 0.04750032,  0.03156645, -0.02608144,  0.03784298,
          0.00595925,  0.00349509, -0.03521048, -0.02863294,
         -0.03503264, -0.03150183],
        [ 0.04750032,  0.03156645, -0.02608144,  0.03784298,
          0.00595925,  0.00349509, -0.03521048, -0.02863294,
         -0.03503264, -0.03150183],
        [ 0.04750032,  0.03156645, -0.02608144,  0.03784298,
          0.00595925,  0.00349509, -0.03521048, -0.02863294,
         -0.03503264, -0.03150183],
        [ 0.04750032,  0.03156645, -0.02608144,  0.03784298,
          0.00595925,  0.00349509, -0.03521048, -0.02863294,
         -0.03503264, -0.03150183],
        [ 0.00721078, -0.02232076,  0.00131174, -0.03862607,
         -0.00124487,  0.01700391, -0.00288004, -0.02921543,
          0.00538623,  0.00024558],
        [-0.00414001, -0.03233385,  0.04409924, -0.00944532,
          0.03331412,  0.03070984,  0.0421849 ,  0.03064516,
         -0.03372888,  0.01382567],
        [ 0.01728043,  0.048831  , -0.04643934,  0.0

In [12]:
embedded_docs[0] ## Sentence 1

array([   0,    0,    0,    0, 8964, 5980, 4592, 9807])